# Generated by Django 5.1.1 on 2024-09-13 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quntity',
            new_name='quantity',
        ),
    ]
